### ISSUE TITLE
Some silkscreen & fab layer elements rendered at wrong place outside of PCB outline

### ISSUE THREAD

**Issue by mMuck** [openscopeproject/InteractiveHtmlBom#482]
Naturally I confirmed the positions of the elements in the PCB project but there they are at correct places.
In the iHtmlBom Canvas they're rendered even somehow rotated. Are there known conditions for such cases?
 
![grafik](https://github.com/user-attachments/assets/350216a0-c44b-4e48-a6f1-b7ffebf509e2)

If this should be investigated I can try to strip down the project to only this elements. Or a snippet of the relevant kicad_pcb file parts if it disappears with less parts.
Compression & zones on, nets off. Current KiCad 8.0.6 (Win10) & latest PCM release of iHtmlBom.

**Comment by qu1ck** [comment]
Already fixed in 002d62760ae2c91a267d8c8d2a3b5eccf81439a2 but it's not released yet.

**Comment by mMuck** [comment]
Wow. Thanks. I see - there are reasons to test the latest master. I'll do that and give feedback.

**Comment by Lambosaurus** [comment]
Hey, I see this is still an issue. Could you do a release to get this fix live?

**Comment by qu1ck** [comment]
Version 2.10.0 is now released.
